### PR TITLE
Add unit test for nodeStatusList

### PR DESCRIPTION
**Pull request by marioCluml**
Added unit test for `nodeStatusList`.  It seems like `accountList` already has unit test in regards to pagination ordering.

Closes: #146 ; Closes: #180 ;

### CODE REVIEW

**Comment by sehkone** [comment]
According to #167, not all combinations are allowed. Does this reflect it?

**Comment by marioCluml** [comment]
> According to #167, not all combinations are allowed. Does this reflect it?

@sehkone Two of the conditions does not follow that rule for the unit test. I will adjust it!

**Comment by marioCluml** [comment]
@sehkone For `nodeStatusList`, it seems the change doesn't effect this GraphQL query. So, it causes an error if I assert for two conditions: (first, before) and (last , after). These two should give an error but I think the queries only applied to the ones in the ChangeLog. Should I remove these conditions from `nodeStatusList` test?

Screenshot 2024-03-19 at 11 52 27 PM

Screenshot 2024-03-19 at 11 52 35 PM

**Review by sophie-cluml — APPROVED** [review]
As discussed over huddle between Mario and Sophie, Mario push-forced a new commit with unwanted parameter combinations removed from the patch. Examples of those removed are (first, before) and (last, after).

However, as Mario indicated https://github.com/aicers/review-web/pull/178#issuecomment-2008807005 in his comment,  #167 does not influence `nodeStatusList` API. So, `nodeStatusList(first: 10, before: "some-hash")` is still a valid GraphQL request. To make that request rejected, we need to add the unwanted-parameter-combination-check code (or param-validation code) to the `nodeStatusList`. And we'd like to tackle that in a separate issue (#180), because we not only need that for `nodeStatusList`, but also for all the other GraphQL APIs that are not covered by #167.

Since the main purpose of this PR and the issue is to add test code that checks the correctness of ordering, and the current state of PR patch does not hamper the modification that is expected to be brough for #167, I am up to merging this patch to the main branch.  @sehkone, I'd like to know your thoughts on this.

**Pull request merged**
