### PR TITLE
Add fields to Node for revert

### PR DESCRIPTION
**Pull request by marioCluml**
Close: #117 

Add two new fields to `Node` for `Revert` and set fields when creating new `Node`

### CODE REVIEW

**Review by sophie-cluml — APPROVED** [review]
LGTM

**Review by dayeon5470 — APPROVED** [review]

**Comment by sophie-cluml** [comment]
@marioCluml Please update changelog.md

**Comment by marioCluml** [comment]
I remember Sehkone talking about how if two commits are independent and complete we wouldn't need to squash it into one commit so I'm wondering if we would need to rebase?

**Comment by sophie-cluml** [comment]
For this PR's case, single commit is more appropriate. The content the the changelog.md and the code change serves the single purpose of add fields to the Node, and it is small enough. So please turn them to a single commit.

**Comment by sophie-cluml** [comment]
Resolved conflicts in CHANGELOG.md by co-authoring the commit [78d1071](https://github.com/aicers/review-web/pull/119/commits/78d10711458cc0bd44f336d43253cd6921250a40)

**Pull request merged**
